# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
pool:
  name: self

steps:
  - task: PowerShell@2
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/az_install.ps1'
  - task: UseDotNet@2
    inputs:
      version: '6.x'

  - script: dotnet restore
    displayName: 'Restore Dependencies'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Build Project'

  - script: dotnet test
    displayName: 'Run Tests'

  - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish Artifact'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'drop'

  # - task: AzureCLI@2
  #   displayName: 'Install Azure Bicep'
  #   inputs:
  #     azureSubscription: 'aks_spn'
  #     scriptType: 'batch'
  #     scriptLocation: 'inlineScript'
  #     inlineScript: 'az bicep install'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**/*.json'
      TargetFolder: '${System.DefaultWorkingDirectory}'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'aks_spn'
      appType: 'webApp'
      appName: 'biceplabdotnet'
      package: '$(System.DefaultWorkingDirectory)/*.zip'
      deploymentMethod: 'auto'
